### ISSUE TITLE
Latex format ? 

### ISSUE THREAD

**Issue by NZR** [Hansschouten/Aircraft-Trajectories#1]
Hello, 

Perhaps it would be wise to split the Latex document into separate files: one for each chapter/main section. It will make future collaborative work somewhat easier. 

Recommendation: 
 keep the main latex file where it is. 
 add a subfolder in that directory called "sections"
 create one .tex file per section in that folder.
 link the different subsection files in the main Latex using the following command : 
   \input{section/my_chapter_latex_file_name_without_the_extension}

Similarly, you can have a subfolder for images. 

Just keep the file tree a bit clean.

Cheers !

**Comment by Ekula** [comment]
Noted! Thanks for the tip!
